language: r
warnings_are_errors: false
sudo: required
dist: trusty
cache: packages

before_install:
  - pip3 install numpy

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate

notifications:
  email:
    on_failure: change

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  

