language: r
warnings_are_errors: false
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes

addons:
  apt:
    packages:
      - python3-numpy
      - python3-matplotlib
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-fonts-recommended
      # - tipa
      # - dvipng

before_install:

install:
  R -e "install.packages('http://cran.r-project.org/src/contrib/Archive/knitr/knitr_1.26.tar.gz', repos=NULL, type='source')"

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate
   - "http://cran.r-project.org/src/contrib/Archive/knitr/knitr_1.26.tar.gz"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

after_failure:
  - ./_retrieve.sh


