language: r
warnings_are_errors: false
# sudo: required
# dist: xenial
cache: packages

addons:
  apt:
    packages:
      - python3-numpy
      - python3-matplotlib

before_install:
  - tlmgr install index

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate
#   - tinytex

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh


