language: r
warnings_are_errors: false
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - python3-numpy
      - python3-matplotlib
      - python3-tk
      
#before_install:
#  - ls -l /usr/bin/python*
#  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#  - python3.4 get-pip.py
#  - python3.4 -m pip install numpy

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate

notifications:
  email:
    on_failure: change

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  

