language: r
warnings_are_errors: false
sudo: required
dist: trusty
cache: packages
pandoc_version: 1.19.2.1

before_install:
  - pip install --upgrade pip
  - pip install numpy matplotlib

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  

