language: r
warnings_are_errors: false
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes

addons:
  apt:
    packages:
      - python3-numpy
      - python3-matplotlib
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      # - tipa
      # - dvipng

before_install:
  - tlmgr update --all --self
  - tlmgr conf texmf TEXMFHOME $(Rscript -e "cat(file.path(R.home('share'), 'texmf'))")

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - reticulate
  - bookdown
  - tinytex
  - rprojroot

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - R -q -e 'if (packageVersion("knitr")>1.26) install.packages("http://cran.r-project.org/src/contrib/Archive/knitr/knitr_1.26.tar.gz", repos=NULL, type="source")'
  - ./_build.sh
  - ./_deploy.sh

after_failure:
  - ./_retrieve.sh


