language: r
warnings_are_errors: false
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes

addons:
  apt:
    packages:
      - python3-numpy
      - python3-matplotlib

before_install:
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
#  - tlmgr install index

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate
#   - tinytex

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh


