# Equations

## Inline equations
...are enclosed by simple `$  $`, like this:

```
$\tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'\,$
```

which produces this output: $\tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'\,$.

## Display equations
...without numbers can be enclosed by double `$$  $$`, like this: 

```
$$\tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'\,.$$
```

which produces

$$\tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'\,.$$

## Equation labels
To label an equation with `name` use the format `(\#eq:name)`. 
To cite that equation use the format `\@ref(eq:name)`

The equation label has to appear after the body of the equation code, like this:
```
\begin{equation} 
  \tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'
  (\#eq:binom)
\end{equation} 
```
\begin{equation}
  \tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'
  (\#eq:binom)
\end{equation}

Then you can cite the equation, like this: \@ref(eq:binom).

## Equation numbering
There is some weirdness about how equation numbering is handled in the PDF versus the HTML versions of the book. 

In the PDF output equations are numbered by default. Every line of an equation will get numbered except if it

1. is inside `$$ $$`.
2. has `\notag` at the end of line, before the `\\`.
3. is in an `{equation*}` or `{align*}` environment where there are no labels
4. is in a `{split}` environment with a single label

But in the HTML output an equation is unnumbered by default, except if it contains an explicit equation label. For more details see [here](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html). 

So, to make sure we get the same numbering in PDF and HTML we should do this:

**An unnumbered display equation** should be enclosed with `$$ $$` or in environments `{equation*}` or `{align*}`.

**A numbered display equation** should include a single label.

Here are some examples:

This equation will get a number in PDF but not in HTML, **which is a mistake!**

\begin{equation} 
  \tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'
\end{equation} 

This gets no number in PDF or HTML:

\begin{equation*} 
  \tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'
\end{equation*} 

And this gets a number in both PDF and HTML:

\begin{equation} 
  \tilde h(\omega) = \int_{-\infty}^{\infty}\,e^{i\omega t'} h(t') \, dt'
  (\#eq:transfu)
\end{equation} 

## Multi-line equation with multiple labels
Here is a long equation stretching over several lines, first with a single number

\begin{equation} 
\begin{split}
\mathrm{Var}(\hat{\beta}) & =\mathrm{Var}((X'X)^{-1}X'y)\\
 & =(X'X)^{-1}X'\mathrm{Var}(y)((X'X)^{-1}X')'\\
 & =(X'X)^{-1}X'\mathrm{Var}(y)X(X'X)^{-1}\\
 & =(X'X)^{-1}X'\sigma^{2}IX(X'X)^{-1}\\
 & =(X'X)^{-1}\sigma^{2}
\end{split}
(\#eq:var-beta1)
\end{equation} 

...then with multiple numbers

\begin{align}
\mathrm{Var}(\hat{\beta}) & =\mathrm{Var}((X'X)^{-1}X'y) \notag \\
 & =(X'X)^{-1}X'\mathrm{Var}(y)((X'X)^{-1}X')'(\#eq:var-a)\\ 
 & =(X'X)^{-1}X'\mathrm{Var}(y)X(X'X)^{-1}(\#eq:var-b)\\ 
 & =(X'X)^{-1}X'\sigma^{2}IX(X'X)^{-1}(\#eq:var-c)\\ 
 & =(X'X)^{-1}\sigma^{2} (\#eq:var-d)
\end{align}

I wrote some grep routines that produce automatic equation labels, for example in the study guide which contains several hundred equations. Every one of those has a label, even though we rarely cite those labels.


